### PR TITLE
Set Rent Type, and 2 Listing Properties

### PR DESCRIPTION
**Pull request by madpin**
Daft:
- Set Renting Type

Listing:
- Distance to City Center
- Public Transport Routes

### CODE REVIEW

**Comment by AnthonyBloomer** [comment]
Great work @madpin! 👍 Thanks for contributing.

**Comment by madpin** [comment]
Hello,

No problem.

Just a question, why do you use this for?
=]

Thanks,
*Thiago MadPin*

*cel:*             +55 11 99614 1038
*website:*      http://madpin.net
*email/msn:*  madpin@gmail.com
*skype:*         madpin

**Comment by AnthonyBloomer** [comment]
Hi @madpin, this was one of the components built as part of my undergraduate thesis. I've continued to work on it since then. It's good that other developers find it useful 👍

**Comment by madpin** [comment]
Hi,

Yes, it's really useful, I'm doing a robot to find the best houses.
I'll be moving to Dublin in november, and I know that it's been really hard
to find a place, and I need to be the first one to send message.

So, I'm doing a robot, with rekognition, tags, and here to calculate the
transport routing to my job.

=]
Thanks,
*Thiago MadPin*

*cel:*             +55 11 99614 1038
*website:*      http://madpin.net
*email/msn:*  madpin@gmail.com
*skype:*         madpin

**Pull request merged**
