### PR TITLE
Improving coverage

### PR DESCRIPTION
**Pull request by AnthonyBloomer**
@sdfordham, I added the set filter method which accepts the MiscFilter enum as argument. Could you please confirm if that's the correct usage? I noticed that the `add_filter` wasn't being called anywhere so added that and some test coverage.

### CODE REVIEW

**Comment by sdfordham** [comment]
I have seen the `MiscFilter` values inside `andFilters` rather than `filters`. I have tested a little adding these just to `filters` and having success but I haven't really figured out how exactly this `andFilters` works in particular what the difference is between `filters`. It needs more testing I think. See below sample POST request from webpage:
```json
{
   "section":"residential-for-sale",
   "filters":[
      {
         "values":[
            "virtual-tour",
            "video"
         ],
         "name":"mediaTypes"
      },
      {
         "values":[
            "houses",
            "detached-houses",
            "semi-detached-houses",
            "terraced-houses",
            "end-of-terrace-houses",
            "townhouses",
            "apartments",
            "studio-apartments",
            "duplexes",
            "bungalows",
            "sites"
         ],
         "name":"propertyType"
      },
      {
         "values":[
            "auction"
         ],
         "name":"saleType"
      },
      {
         "values":[
            "sale-agreed"
         ],
         "name":"adState"
      }
   ],
   "andFilters":[
      {
         "values":[
            "alarm",
            "gas-fired-central-heating",
            "oil-fired-central-heating",
            "parking",
            "wheelchair-access",
            "wired-for-cable-television"
         ],
         "name":"facilities"
      }
   ],
   "ranges":[
      {
         "from":"20",
         "to":"30",
         "name":"floorSize"
      },
      {
         "from":"3",
         "to":"4",
         "name":"numBaths"
      },
      {
         "from":"5",
         "to":"9",
         "name":"numBeds"
      },
      {
         "from":"175000",
         "to":"300000",
         "name":"salePrice"
      },
      {
         "from":"2",
         "to":"12",
         "name":"ber"
      },
      {
         "from":"now-7d/d",
         "to":"",
         "name":"firstPublishDate"
      }
   ],
   "paging":{
      "from":"0",
      "pageSize":"20"
   },
   "geoFilter":{
      "storedShapeIds":[
         "19_3000"
      ],
      "geoSearchType":"STORED_SHAPES"
   },
   "terms":"Keyword1",
   "sort":"priceAsc"
}
```

**Comment by AnthonyBloomer** [comment]
Nice one, thanks! I'll remove the `set_filter` method for now and will do some more testing into this.

**Comment by EricNeville** [comment]
In the version I was personally using I have added functionality for filtering by facilities in andFilters. The process I used was to add a method to daft.py identical to _add_filters() except it adds to andFilters instead. Then a set_facilities() method is adding any facility to andFilters through this function. This was working for me. I hadn't added any type checking but it seems like it would make sense to do this by adding a Facilities Enum to enums.py and including all of the allowable facilities listed in the discussion thread on V2 design (https://github.com/AnthonyBloomer/daftlistings/discussions/88#discussioncomment-518575). 

If this seems like a good way to manage this I'm happy to add the type checking to what I already have and push this, but it doesn't deal with all of the MiscFilters as it looks like they don't all come under facilities.

**Comment by sdfordham** [comment]
Some of `MiscFilters` appear not to go in `andFilters` e.g. `AUCTION`, `VIRTUAL_TOUR`, `SALE_AGREED` at least the POST requests from webpage suggest this.
I would extract from `MiscFilters` into your new enum `Facilities` those that work in `andFilters`. Your approach seems fine, r.e. adding `._set_add_filter()`, `.set_facilities()` methods.

Generally one opens a new issue for this sort of thing. Or you can just make the changes and make a pull request,  if there is something wrong someone will bring it up in the pull request and then there's the opportunity to amend the pull request with another commit or close it without merging etc.

**Pull request merged**
